# Generated by Django 2.2.24 on 2021-09-10 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_category', '0001_initial'),
        ('course_overviews', '0024_overview_adds_has_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='course_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_category.CourseCategory'),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='course_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_category.CourseCategory'),
        ),
    ]
